### ISSUE TITLE
Change text on final page

### ISSUE THREAD

**Issue by pdcamilleri** [pdcamilleri/WMIF#105]
Final page: Give this page a title “Study Complete!” Also, can you please make a box on the admin page where I can control (1) the words that go in the box, and (2) the completion code.  For this study, I don’t need the sentence (an associated calculation) “Note, the next review score for the product that you chose was 9”.

**Comment by pdcamilleri** [comment]
@ac11ca what box?

**Comment by ac11ca** [comment]
I need two text boxes on the admin page to control the final page participants see

Date: Tue, 31 Mar 2015 15:17:40 -0700
