### ISSUE TITLE
Can't access SWED results 

### ISSUE THREAD

**Issue by mirraseigerman** [pdcamilleri/WMIF#65]
I can't seem to access the results page anymore. Here is the procedure I followed:

In the start page (http://adriancamilleri.net/WMIF/start.php?MID=mturkid) I entered some random ID in place of "mturkid" (e.g., 12345) and then complete the survey ---> then I  copy and paste this link in a new tab: http://adriancamilleri.net/WMIF/results/mid.txt and simply replace mid with "12345" ---> all I get is an error page instead of a line of values as before.

**Comment by pdcamilleri** [comment]
This was a one-off issue where the output file wasn't created. Closing.
