### ISSUE TITLE
Not presenting multiple problems

### ISSUE THREAD

**Issue by ac11ca** [pdcamilleri/WMIF#70]
In the CSV file, every row is a new problem (i.e. choice between two new products). In the current CSV file there are four rows (i.e., 4 choices must be made; 8 total products presented during the experiment). Currently, the experiment ends after making the first choice. There is no second choice. Also, the order of the problems presented should be randomized and recorded in the datafile so that I can later reconstruct the exact experience of every participant.

**Comment by pdcamilleri** [comment]
Did multiple problems, which is presented randomly.

Order of problems is stored in database as the problem number. First problem presented is problem 1.

Whether or not the two options were switched also recorded.
