### ISSUE TITLE
Column Headings

### ISSUE THREAD

**Issue by mirraseigerman** [pdcamilleri/WMIF#72]
I'm still having trouble discerning what the values in each column represent. As Adrian mentioned in his last email, it would be great if you could create headings for each column so that each column is really clear once loaded into excel.

**Comment by mirraseigerman** [comment]
I think this is also done no?

**Comment by pdcamilleri** [comment]
Yep, this has been done as part of d21cbef2b7ea9d8b9239ec732a378b24d3254aa4
