### ISSUE TITLE
Choice_strength

### ISSUE THREAD

**Issue by mirraseigerman** [pdcamilleri/WMIF#81]
Looks like the choice_strength scale is only running from 1-6 (in the output) as opposed to 1-7 (in the survey). In the mirra_2 trial, I selected "Strongly Prefer Product 2" for problem 1 and 2 (i.e., 7/7) and they are represented here as a 6 instead of a 7.

**Comment by pdcamilleri** [comment]
Just did a couple tests with mid=peter_6 and it seemed to be working as expected (correctly got 7/7). 

Will need to examine further. Maybe something else in the experiment is affecting this. But going to put aside for now and come back to it later.

**Comment by pdcamilleri** [comment]
@mirraseigerman same as #81, can you test this again please and record what you are selecting in the textbox on the same page.

**Comment by mirraseigerman** [comment]
I did this for mirra_3 and it all worked - nice work!
