### ISSUE TITLE
Friend_recommendation

### ISSUE THREAD

**Issue by mirraseigerman** [pdcamilleri/WMIF#82]
friend_recommendation - output is out of sync with entry:

As mirra_2 my selections were:
Problem 0: incorrect - I chose "very unlikely" (7/7) but the value in excel is 6
Problem 1: correct - I chose "very likely" (1/7) and 1 was the value in excel
Problem 2: correct - I chose "very likely" (1/7) and 1 was the value in excel
Problem 3: incorrect - I chose "neutral" (4/7) but the value in excel is 7

**Comment by pdcamilleri** [comment]
Probably related to #81, will also come back to this later as I cannot reproduce the problem.

**Comment by pdcamilleri** [comment]
@mirraseigerman Can you test this again please?

Also when testing, in the box on the survey page that says "Please explain why you choose this option?", can you please write what options you are selecting for both the choice_strength and friend_recommendation options?

**Comment by mirraseigerman** [comment]
Looks like this is all working now! :-)
