### ISSUE TITLE
experience a and b columns

### ISSUE THREAD

**Issue by mirraseigerman** [pdcamilleri/WMIF#84]
From trial as mirra_2:
experience a columns are incorrect (i.e., values don't represent those that I saw) - they are correct for problem 0 but incorrect for the remaining problems (it looks like problem 0 values have just been copied into these columns). 

same for experience b columns. They are correct for problem a but incorrect for remaining problems. In fact it looks like the rest of the columns are problematic - i.e., don't correspond to what the column label says.

**Comment by pdcamilleri** [comment]
It looks like the experience values are being added to and not replaced, and this affects the rest of the CSV file. Just a simple look shows that the lines after the first problem are longer than they should be which again points to values not being replaced properly. And I think this issue has the carryon effect of knocking the remaining columns out of sync
