### ISSUE TITLE
Collapsing data from multiple participants

### ISSUE THREAD

**Issue by mirraseigerman** [pdcamilleri/WMIF#91]
Peter, so far we've only been checking how to extract data from single trials. I'm wondering how we are going to approach data collection for larger samples - e.g., 50 + 
It will be extremely time consuming to have to extract data from each individual and format it into an excel spreadsheet. Is there any way of collecting data from multiple trials in one csv output page?

**Comment by pdcamilleri** [comment]
This will be easy to do once the data has been gathered and stored in the database. I already did something like this a little while ago, see http://adriancamilleri.net/WMIF/csv.php (scroll down to the bottom).
